apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ckan
  namespace: "1004960885194"
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: DESCRIPTION
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/container-dependencies: CONTAINER_START_ORDER
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1004960885194-compute@developer.gserviceaccount.com
      containers:
        - image: docker.io/jeevanexa/ckan-docker-nginx:latest
          name: nginx
          ports:
            - name: http1
              containerPort: 443
          env:
            - name: NGINX_CONTAINER_NAME
              value: nginx
            - name: REDIS_CONTAINER_NAME
              value: redis
            - name: POSTGRESQL_CONTAINER_NAME
              value: db
            - name: SOLR_CONTAINER_NAME
              value: solr
            - name: DATAPUSHER_CONTAINER_NAME
              value: datapusher
            - name: CKAN_CONTAINER_NAME
              value: ckan
            - name: WORKER_CONTAINER_NAME
              value: ckan-worker
            - name: CKAN_PORT_HOST
              value: 5000
            - name: NGINX_PORT_HOST
              value: 81
            - name: NGINX_SSLPORT_HOST
              value: 8443
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: db
            - name: CKAN_DB_USER
              value: ckandbuser
            - name: CKAN_DB_PASSWORD
              value: ckandbpassword
            - name: CKAN_DB
              value: ckandb
            - name: DATASTORE_READONLY_USER
              value: datastore_ro
            - name: DATASTORE_READONLY_PASSWORD
              value: datastore
            - name: DATASTORE_DB
              value: datastore
            - name: CKAN_SQLALCHEMY_URL
              value: postgresql://ckandbuser:ckandbpassword@db/ckandb
            - name: CKAN_DATASTORE_WRITE_URL
              value: postgresql://ckandbuser:ckandbpassword@db/datastore
            - name: CKAN_DATASTORE_READ_URL
              value: postgresql://datastore_ro:datastore@db/datastore
            - name: TEST_CKAN_SQLALCHEMY_URL
              value: postgres://ckan:ckan@db/ckan_test
            - name: TEST_CKAN_DATASTORE_WRITE_URL
              value: postgresql://ckan:ckan@db/datastore_test
            - name: TEST_CKAN_DATASTORE_READ_URL
              value: postgresql://datastore_ro:datastore@db/datastore_test
            - name: CKAN_VERSION
              value: 2.10.0
            - name: CKAN_SITE_ID
              value: default
            - name: CKAN_SITE_URL
              value: https://localhost:8443
            - name: CKAN_PORT
              value: 5000
            - name: CKAN_PORT_HOST
              value: 5000
            - name: CKAN___BEAKER__SESSION__SECRET
              value: CHANGE_ME
            - name: CKAN___API_TOKEN__JWT__ENCODE__SECRET
              value: string:CHANGE_ME
            - name: CKAN___API_TOKEN__JWT__DECODE__SECRET
              value: string:CHANGE_ME
            - name: CKAN_SYSADMIN_NAME
              value: ckan_admin
            - name: CKAN_SYSADMIN_PASSWORD
              value: test1234
            - name: CKAN_SYSADMIN_EMAIL
              value: your_email@example.com
            - name: CKAN_STORAGE_PATH
              value: /var/lib/ckan
            - name: CKAN_SMTP_SERVER
              value: smtp.corporateict.domain:25
            - name: CKAN_SMTP_STARTTLS
              value: true
            - name: CKAN_SMTP_USER
              value: user
            - name: CKAN_SMTP_PASSWORD
              value: pass
            - name: CKAN_SMTP_MAIL_FROM
              value: ckan@localhost
            - name: TZ
              value: UTC
            - name: SOLR_IMAGE_VERSION
              value: 2.10-solr9
            - name: CKAN_SOLR_URL
              value: http://solr:8983/solr/ckan
            - name: TEST_CKAN_SOLR_URL
              value: http://solr:8983/solr/ckan
            - name: REDIS_VERSION
              value: 6
            - name: CKAN_REDIS_URL
              value: redis://redis:6379/1
            - name: TEST_CKAN_REDIS_URL
              value: redis://redis:6379/1
            - name: DATAPUSHER_VERSION
              value: 0.0.20
            - name: CKAN_DATAPUSHER_URL
              value: http://datapusher:8800
            - name: CKAN__DATAPUSHER__CALLBACK_URL_BASE
              value: http://ckan:5000
            - name: DATAPUSHER_REWRITE_RESOURCES
              value: true
            - name: DATAPUSHER_REWRITE_URL
              value: http://ckan:5000
            - name: NGINX_PORT
              value: 80
            - name: NGINX_SSLPORT
              value: 443
            - name: CKAN__PLUGINS
              value: "envvars image_view text_view recline_view datastore datapusher"
            - name: CKAN__HARVEST__MQ__TYPE
              value: redis
            - name: CKAN__HARVEST__MQ__HOSTNAME
              value: redis
            - name: CKAN__HARVEST__MQ__PORT
              value: 6379
            - name: CKAN__HARVEST__MQ__REDIS_DB
              value: 1
          startupProbe:
            tcpSocket:
              port: 443
            timeoutSeconds: 240
            failureThreshold: 5
            periodSeconds: 240
        - image: docker.io/library/redis:6
          name: redis
        - image: docker.io/ckan/ckan-solr:2.10-solr9
          name: solr
        - image: docker.io/jeevanexa/ckan-docker-db:latest
          name: db
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: CKAN_DB_USER
              value: ckandbuser
            - name: CKAN_DB_PASSWORD
              value: ckandbpassword
            - name: CKAN_DB
              value: ckandb
            - name: DATASTORE_READONLY_USER
              value: datastore_ro
            - name: DATASTORE_READONLY_PASSWORD
              value: datastore
            - name: DATASTORE_DB
              value: datastore
        - image: docker.io/ckan/ckan-base-datapusher:0.0.20
          name: datapusher
        - image: docker.io/jeevanexa/ckan-docker-ckan:latest
          name: ckan

  traffic:
    - percent: 100
      latestRevision: true
